module "backend_v2" {
  source                = "../../../base/backend/v2"
  image_name            = "${var.image_name}"
  flavor_name           = "${var.flavor_name}"
  key_pair              = "${var.key_pair}"
  backend_name          = "${var.backend_name}"
  backend_ansible_group = "${var.backend_ansible_group}"
  bastion_name          = "${var.bastion_name}"
  bastion_ansible_group = "${var.bastion_ansible_group}"
  external_net          = "${var.external_net}"
  backend_net           = "${var.backend_net}"
  backend_cidr          = "${var.backend_cidr}"
  bastion_net           = "${var.bastion_net}"
  bastion_cidr          = "${var.bastion_cidr}"
  gateway_name          = "${var.gateway_name}"
  nb_backend            = "${var.nb_backend}"
}
